### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by jochenpee** [raycoarana/poi-to-discover-media#1]
The instructions in the README do not work, because there is no bin folder. How can I build the program?

**Comment by raycoarana** [comment]
If you are using the source-code, you will find the binary in the bin folder. In the README it is explained how to use the release. To build the program you just have to build it with Gradle as any other Java program.

**Comment by jochenpee** [comment]
I downloaded the zip file, there is no bin folder.
This is the first time I hear about gradle, just installed it. "gradle build" did not do much. Build instructions would be great.

**Comment by raycoarana** [comment]
Friend, there is a bin folder inside the release ZIP file, please double check. You don't need to compile if you use the release ZIP.

**Comment by jochenpee** [comment]
I wish it were.

jochen@compi:~/poi-to-discover-media-master$ ls
build.gradle.kts  gradle  gradlew  gradlew.bat  LICENSE  README.md  settings.gradle  src
jochen@compi:~/poi-to-discover-media-master$ find . -name bin
jochen@compi:~/poi-to-discover-media-master$

**Comment by raycoarana** [comment]
You are not downloading the release ZIP file, you are downloading the repo source-code...

Please head to releases: https://github.com/raycoarana/poi-to-discover-media/releases

**Comment by jochenpee** [comment]
Just found the "releases" tab...
