### ISSUE TITLE
Does this work for MIB2STD?

### ISSUE THREAD

**Issue by ShifengHuGit** [raycoarana/poi-to-discover-media#2]
I saw your code to generate the Metainfo2.txt,  there were no Signature lines, so I am wondering does it work for MIB2STD without the Signature lines

**Comment by raycoarana** [comment]
Is what I have in my car, a Composition Media (MIB2STD), and yes it works. Signature is not used and I removed it.

**Comment by ShifengHuGit** [comment]
OK, thnx for your quickly reply.  it not work for mine without a valid Signature information. Probably your module's vendor  is Dephi, but mine is Techinsat,  much more limitations rather yours....
